### PR TITLE
improve error message when missing compiler binary and allow custom binary paths

### LINKED ISSUE #48: Raise a better error when compiler is not found in PATH
When the compiler is not found we let `OSError: [Errno 2] No such file or directory` be thrown. We should return a better error and a better message like `Executable {name} not found`.

Full stacktrace of an example:
```sh
Traceback (most recent call last):
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask_cache/__init__.py", line 297, in decorated_function
    rv = f(*args, **kwargs)
  File "/Users/liuyiqi/code/src/opendata/app/home/views.py", line 9, in index
    return render_template('home.html')
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/liuyiqi/code/src/opendata/app/templates/home.html", line 3, in top-level template code
    {% extends 'layouts/base.html' %}
  File "/Users/liuyiqi/code/src/opendata/app/templates/layouts/base.html", line 26, in top-level template code
    {% compress 'css' %}
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/jac/extension.py", line 39, in _compress_block
    return self.compressor.compress(html, compression_type)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/jac/base.py", line 103, in compress
    debug=self.config.compressor_debug)
  File "/Users/liuyiqi/venv/opendata/lib/python2.7/site-packages/jac/compressors/less.py", line 35, in compile
    stderr=subprocess.PIPE, cwd=None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

### PR DESCRIPTION
**Pull request by alanhamlett**
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/jinja-assets-compressor/50)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 173 at r1](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50#-KfV4WRme-hVxdZFzMKq:-KfV4WRme-hVxdZFzMKr:b-7aweih) ([raw file](https://github.com/jaysonsantos/jinja-assets-compressor/blob/94094d9d94c9f39abb9e9a53b129e0eb112db51e/README.md#L173)):*
> ```Markdown
> ```
> 
> To only customize the path of a compressor which forks a subprocess for the
> ```

This is good but what do you think about allowing overriding it with configs?

---

*[jac/compressors/coffee.py, line 35 at r1](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50#-KfV4d_97jfiytxIQlW4:-KfV4d_97jfiytxIQlW5:b-mugegm) ([raw file](https://github.com/jaysonsantos/jinja-assets-compressor/blob/94094d9d94c9f39abb9e9a53b129e0eb112db51e/jac/compressors/coffee.py#L35)):*
> ```Python
>                                        stderr=subprocess.PIPE, cwd=None)
>         except OSError:
>             msg = '{0} can\'t find {1}. Make sure {1} is in your PATH.'.format(
> ```

This is only true if `OSError().errno == errno.ENOENT`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50)*

**Comment by alanhamlett** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 173 at r1](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50#-KfV4WRme-hVxdZFzMKq:-KfVPfjS30JvxOntohOx:bbykxu4) ([raw file](https://github.com/jaysonsantos/jinja-assets-compressor/blob/94094d9d94c9f39abb9e9a53b129e0eb112db51e/README.md#L173)):*
<details><summary><i>Previously, jaysonsantos (Jayson Reis) wrote…</i></summary><blockquote>

This is good but what do you think about allowing overriding it with configs?
</blockquote></details>

I'm not sure how to design that so it would work when a subprocess is not used, like JavaScriptCompressor.

---

*[jac/compressors/coffee.py, line 35 at r1](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50#-KfV4d_97jfiytxIQlW4:-KfVQQHTo7nge0nBRk2o:b-896fix) ([raw file](https://github.com/jaysonsantos/jinja-assets-compressor/blob/94094d9d94c9f39abb9e9a53b129e0eb112db51e/jac/compressors/coffee.py#L35)):*
<details><summary><i>Previously, jaysonsantos (Jayson Reis) wrote…</i></summary><blockquote>

This is only true if `OSError().errno == errno.ENOENT`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50)*

**Comment by jaysonsantos** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/50)*

**Comment by jaysonsantos** [comment]
Thanks again @alanhamlett !

**Pull request merged**
