### PR TITLE
offline compression script py3 support and app root_path detection

### PR DESCRIPTION
**Pull request by alanhamlett**
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/jinja-assets-compressor/35)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Travis broke because of the coverage thingy, probably they changed the way it works.

**Comment by alanhamlett** [comment]
Updating the dependencies to latest versions doesn't change anything (#36) and I can't get this error to occur locally.

**Comment by jaysonsantos** [comment]
Can you merge master again?

**Comment by alanhamlett** [comment]
Rebased my fork with the latest code and Travis ran tests again, but still failing.

https://github.com/alanhamlett/jinja-assets-compressor/commits/master

**Comment by jaysonsantos** [comment]
I tested it locally, I will just merge it. Thanks!

**Pull request merged**
