### PR TITLE
setup tox

### PR DESCRIPTION
**Pull request by alanhamlett**
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/jinja-assets-compressor/56)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Thanks again @alanhamlett. Can you already change travis? I created a patched based on your changes to make it run with tox (i hope it works) and also I put the installation in another file to avoid installing every time.
Here it goes:

```patch
diff --git a/.travis-install.sh b/.travis-install.sh
deleted file mode 100755
index 1b9d15a..0000000
--- a/.travis-install.sh
+++ /dev/null
@@ -1,7 +0,0 @@
-#!/bin/bash
-set -e
-set -x
-pip install -r requirements_tests.txt
-gem install sass
-npm install -g less
-npm install -g coffee-script
diff --git a/.travis.yml b/.travis.yml
index fd51139..a31bfdf 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,10 +1,21 @@
 language: python
-python:
-  - "2.7"
-  - "3.4"
-  - "3.5"
-  - "3.6"
-install: ./.travis-install.sh
+sudo: false
+cache: pip
+matrix:
+  include:
+    - python: "2.7"
+      env:
+        - TOXENV=py27
+    - python: "3.4"
+      env:
+        - TOXENV=py34
+    - python: "3.5"
+      env:
+        - TOXENV=py35
+    - python: "3.6"
+      env:
+        - TOXENV=py26
+install:
+  - pip install tox
 script:
-  - make coverage
-  - make lint
+  - tox -v
diff --git a/install-dependencies.sh b/install-dependencies.sh
new file mode 100755
index 0000000..15c63a2
--- /dev/null
+++ b/install-dependencies.sh
@@ -0,0 +1,6 @@
+#!/bin/bash
+set -e
+set -x
+which sass || gem install sass
+which lessc || npm install -g less
+which coffee || npm install -g coffee-script
diff --git a/tox.ini b/tox.ini
index 2619db6..77a10c2 100644
--- a/tox.ini
+++ b/tox.ini
@@ -4,8 +4,6 @@ envlist = py27, py34, py35, py36
 deps =
     -rrequirements_tests.txt
 commands =
-    gem install sass
-    npm install -g less
-    npm install -g coffee-script
+    ./install-dependencies.sh
     make coverage
     make lint
```

**Comment by jaysonsantos** [comment]
The idea is just to avoid having the same installs both in tox.ini and .travis.yml

**Comment by alanhamlett** [comment]
Travis can run tests in parallel on multiple versions of Python at the same time. If we use tox to run tests on Travis, we chain tests and loose the ability to run in parallel.

**Comment by jaysonsantos** [comment]
The matrix on travis.yml that I put on is to do that, it will call tox only for the build it is doing which will also be parallel I got the idea from this cookiecutter https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/.travis.yml

**Comment by alanhamlett** [comment]
Oh, didn't see that. Yea, then it limits tox to only one environment and uses Travis to parallelize. I'll change it now.

**Comment by jaysonsantos** [comment]
Thanks @alanhamlett !

**Pull request merged**
