### PR TITLE
use subfolder for default flask static output dir

### PR DESCRIPTION
**Pull request by alanhamlett**
This is a better default, to keep original static files separate from compressed files.

---
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/jinja-assets-compressor/45)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Hey @alanhamlett it looks good but a test failed trying to concatenate a Mock to str, could you take a look on it?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/45#-:-KZRvZNL-v6jOarHat8J:b-kp1rmj)*

**Comment by jaysonsantos** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/45)*

**Comment by alanhamlett** [comment]
@jaysonsantos fixed the tests

**Comment by jaysonsantos** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/45)*

**Comment by jaysonsantos** [comment]
Thanks @alanhamlett !

**Pull request merged**
