### PR TITLE
allow custom compressor classes to fix #7

### LINKED ISSUE #7: Allow configuring compiler commands
For changing compiler programs and their arguments.

Follow the django-compressor convention of mime-type to compiler command which is passed to str.format()

    COMPILERS = (
        # ('text/coffeescript', 'coffee --compile --stdio'),
        # ('text/less', 'lessc {infile} {outfile}'),
        # ('text/x-sass', 'sass {infile} {outfile}'),
        # ('text/stylus', 'stylus < {infile} > {outfile}'),
        # ('text/x-scss', 'sass --scss {infile} {outfile}'),
    )

### PR DESCRIPTION
**Pull request by alanhamlett**
This adds a new environment config `compressor_classes` with defaults:

```
{
    'text/css': LessCompressor,
    'text/coffeescript': CoffeeScriptCompressor,
    'text/less': LessCompressor,
    'text/javascript': JavaScriptCompressor,
    'text/sass': SassCompressor,
    'text/scss': SassCompressor,
}
```

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Thank you @alanhamlett, do you need a release of it?

**Comment by alanhamlett** [comment]
Nope, I'm not in need of this but @urbaniak would probably appreciate a release. Glad to have helped :)

**Comment by alanhamlett** [comment]
@jaysonsantos thanks for bumping the version so fast, running this in production already :+1:

**Comment by jaysonsantos** [comment]
Good to hear it :)

**Pull request merged**
