### PR TITLE
improve performance to fix #46

### LINKED ISSUE #46: This tool is too slow, how to improve？

### PR DESCRIPTION
**Pull request by alanhamlett**
This change is [Reviewable](https://reviewable.io/reviews/jaysonsantos/jinja-assets-compressor/47)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jaysonsantos/jinja-assets-compressor/47)*

**Comment by jaysonsantos** [comment]
Did you see much improvement?
Thanks again!

**Comment by alanhamlett** [comment]
Yes, dev templates render much faster now.

**Comment by jaysonsantos** [comment]
Great!

**Comment by alanhamlett** [comment]
When can we expect the next patch release to go on pypi?

**Comment by jaysonsantos** [comment]
I can do it now, I will 0.16 because #45 changed the default behavior

**Comment by alanhamlett** [comment]
Thanks!

**Pull request merged**
